services:
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile.api
    image: shipping-api
    container_name: shipping-api
    restart: unless-stopped
    environment:
      SERVER_PORT: "8080"
      DB_HOST: ${DB_HOST:-ec-demo-mysql-8}
      DB_PORT: "3306"
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-123456}
      DB_NAME: ${DB_NAME:-shipping}
      KAFKA_ENABLED: "false"
      JWT_PRIVATE_KEY_PATH: /app/keys/jwt-private.pem
      JWT_PUBLIC_KEY_PATH: /app/keys/jwt-public.pem
      JWT_ISSUER: shipping-service
      JWT_AUDIENCE: shipping-service
      JWT_ACCESS_TOKEN_DURATION: "15"
      JWT_REFRESH_TOKEN_DURATION: "7"
    ports:
      - "8080:8080"
    networks:
      - jason-lab-net

networks:
  jason-lab-net:
    external: true
